# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

variables:
  tag: '$(Build.BuildId)'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@1
  displayName: 'Build image'
  inputs:
    azureSubscriptionEndpoint: 'fgids00502connection'
    azureContainerRegistry: expsettingregistry.azurecr.io
    useDefaultContext: false
    imageName: 'containerwebapp'
    dockerFile: ContainerWebApp/Dockerfile

- task: Docker@1
  displayName: 'Push image'
  inputs:
    azureSubscriptionEndpoint: 'fgids00502connection'
    azureContainerRegistry: expsettingregistry.azurecr.io
    command: 'Push an image'
    imageName: 'containerwebapp'

- task: PublishBuildArtifacts@1
  displayName: 'Publish ARM template'
  inputs:
    PathtoPublish: 'ContainerWebApp.ResourceGroup'
    ArtifactName: template